### ISSUE TITLE
Portable browser

### ISSUE THREAD

**Issue by djinnsynth** [r52/pta-next#11]
Tagging as request because this issue is way beyond the scope of your project, but may be doable?

I recently setup Firefox as a portable program and now (unsuprisingly) PTA doesn't know what to do when I ask it to "open in pathofexile.com" 

Do you think there would be a way to designate the location of a portable browser for that button? Otherwise I might just have to reinstall Firefox as non portable.

Let me know what you think.

**Comment by r52** [comment]
The function of the `open in pathofexile.com` button (as well as a bunch of other functions in the app that is supposed to open URLs in your native browser) delegates this functionality to the OS. On Windows, this is controlled by `Default apps` settings (you can find this by searching for "Default apps" in the start menu), or more specifically, the `Web browser` setting under Default apps. If you can find a way to get your copy of portable Firefox listed/set there then it will work again automatically.

I definitely do not want to be adding custom browser target support, nor do I want to go the PoE-Overlay route of using an internal browser, as both these options open up a new can of worms that I have no taste for in terms of what I expect out of my desired PoE tool.

Hope this helps.

**Comment by djinnsynth** [comment]
Yep all good! 

I'm actually able to set the portable one manually so it's working out fine now :)

Cheers!
