### ISSUE TITLE
JavaScript Error?

### ISSUE THREAD

**Issue by djinnsynth** [r52/pta-next#4]
First off this new version looks super promising! Great work!

Ok bug report time:

I get this when I try to send a trade to myself to check settings:

![image](https://user-images.githubusercontent.com/60988604/78613601-9d300000-78af-11ea-8beb-9a04f0be95ce.png)

I'm not sure why tho? Haven't been able to checl if it does it when another player sends me a trade but I'd imagine it'd be the same.

**Comment by r52** [comment]
Whoops, misspelled a variable. Fixed in 52b371f.
