### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by djinnsynth** [r52/pta-next#5]
Some things I've missed from other similar tools:

- Being able to hold a modifier key with trade site open that will copy trade whisper > switch to PoE window > paste trade whisper. This could be written in a seperate .ahk script (like I actually have now while using PTANext) but having this built in would be great!

- Having multiple trades be tabbed instead of stacked on top of each other! I find that if I get spammed I quickly run out of screen space. For reference here a screen of another tools interface with tabs:

![image](https://user-images.githubusercontent.com/60988604/78835784-24a67c00-7a34-11ea-8024-d6254c5d1fc8.png)

This tool also highlights the number on the tab a different colour depending on a few conditions:

Green: Player has entered your hideout, lets you know you can send trade.
Pink: Player has sent an additional whisper after initial trade message, this is useful for offers.

- Bring back hotkey for wiki lookup! That feature was verrrrrry useful! 

I  think there were afew other things but I can't think of them right now.

Keep up the awesome work!

**Comment by r52** [comment]
TODO List (and some implementation notes for myself):

- [ ] Port wiki lookup feature (this one was actually added by @Rottenbeer in the original PTA)
- [ ] Modifier Key to quick paste trade whispers
  - Couple of technical annoyances to sort out with regards to implementing this in JS, such as detecting/saving/searching for PoE window and switching to it.
  - Alt seems to work fine on Firefox, not sure if having the option to set this key is a good idea.
- [ ] Tabbed trade notifications
  - The design for this one is probably gonna be painful. Need to figure out how to best customize the library's UI components to fit the dialog and current design without making it too big or cluttered.

**Comment by r52** [comment]
Turns out Alt for quick whisper is a no go, because Alt + Enter changes the game's fullscreen mode.

**Comment by r52** [comment]
Added first pass implementation of tabbed notifications. Give it a try and let me know if there are any issues.

**Comment by djinnsynth** [comment]
Hmm the DL from the builds page doesn't seem to be working. I'm not currently able to build myself.

**Comment by djinnsynth** [comment]
Ok the AppVeyor DL is working!

**Comment by r52** [comment]
Closing this as completed. Any further tweaks, modifications, or other requests can be done in a new issue.
