### ISSUE TITLE
Corrupted mods on weapon

### ISSUE THREAD

**Issue by Wobein** [r52/pta-next#7]
Weapon corruption is not determined. 
![image](https://i.imgur.com/BMq8xta.jpg)

**Comment by r52** [comment]
I couldn't replicate this (before current changes, see image). However, I did fix an issue with values for corrupted implicits. Please try again with the latest dev build.

![image](https://user-images.githubusercontent.com/9069578/80322957-15b61c80-87dd-11ea-928a-3664a21878e5.png)

**Comment by Wobein** [comment]
Yes, there are no more problems with this. The mod is detected correctly. I apparently used an early build and did not update as the version did not change. Thanks for the answer.
